In [2]:
import torch

In [3]:
import numpy as np
import torch.nn as nn

In [13]:
np1 = np.random.rand(3, 4)
np1


array([[0.41582104, 0.54014328, 0.94767384, 0.81200543],
       [0.891864  , 0.93261644, 0.09048668, 0.99375229],
       [0.95240622, 0.70228141, 0.98000575, 0.00983697]])

In [10]:
tensor = torch.rand(3, 4)
tensor

tensor([[0.9474, 0.6644, 0.8351, 0.5190],
        [0.3050, 0.0196, 0.8621, 0.6367],
        [0.7717, 0.5494, 0.1921, 0.5648]])

In [11]:
tensor = torch.randn(3, 4)
print(tensor)
print(tensor.size())
print(tensor[0])
print(tensor.dtype)
tensor1 = torch.tensor(np1)
print(tensor1)
print(tensor1.dtype)
tesnor2 = torch.tensor([1, 2, 3])
print(tesnor2)
print(tesnor2.dtype)

tensor([[-0.2976, -0.5314, -0.3171, -0.6162],
        [-1.8430, -0.6917, -0.5225,  0.0506],
        [-0.3663, -0.0273,  0.2137,  0.7366]])
torch.Size([3, 4])
tensor([-0.2976, -0.5314, -0.3171, -0.6162])
torch.float32
tensor([[0.9512, 0.4568, 0.2774, 0.4793],
        [0.0588, 0.3883, 0.8460, 0.6828],
        [0.7955, 0.3268, 0.3857, 0.3728]], dtype=torch.float64)
torch.float64
tensor([1, 2, 3])
torch.int64


torch.rand()	Uniform [0, 1)	Positive only	        Normalized data, probabilities
torch.randn()	Normal (mean=0)	Positive & negative	    Neural net weights, noise

In [31]:
my_torch = torch.arange(10)
print(my_torch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [32]:
my_torch1 = my_torch.view(2, 5)
my_torch1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [33]:
my_torch2 = my_torch.view(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [34]:
my_torch[1] = 100
my_torch

tensor([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [35]:
my_torch1 # autmaticaally updated 

tensor([[  0, 100,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [45]:
my_torch3 = my_torch.reshape(5, 2)
my_torch3

tensor([[  0, 100],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [46]:
my_torch3 = my_torch3[ :,1: ]
my_torch3

tensor([[100],
        [  3],
        [  5],
        [  7],
        [  9]])